name: Shell Commands

on: [push]

jobs:
  
  runs-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: eccho a string
        run: eccho "Hello World"

      - name: multiline script
        run: |

          node -v
          npm -v
